a = print("     *")
b = print("    * *")
c = print("   *   *")
d = print("  *     *")
e = print(" *       *")
f = print("****   ****")
g = print("   *   *","   *   *","   *   *", sep = "\n")
h = print("   *****")

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
